name: Docker Build

on:
  push:
    branchs:
      - master
    tags:
      - '*'

jobs:
  build-image:
    if: secrets.DOCKER_REPO
    runs-on: ubuntu-latest
    name: Docker Image
    steps:
      - uses: actions/checkout@master
      - run: |
          imgtags=$(echo "${{ github.ref }}" | sed 's/refs\/tags\//latest,/; s/refs\/heads\///')
          echo "::set-env name=imgtags::$imgtags"
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: "$imgtags"
